# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='matriucla',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
        migrations.AddField(
            model_name='team',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
